### ISSUE TITLE
typeError when creating a new package

### ISSUE THREAD

**Issue by sumanthreddybolledla** [dxatscale/sfp-cli#55]
**Describe the bug**
I'm trying to use sfp-cli and I'm receiving a TypeError when trying to create a new package for new metadata synced from dev org to local. This happens during "sfp sync" 

**To Reproduce**
1) Create a work item and assign a branch to it using "sfp work"
2) Add new components in the dev org., eg: add a new custom field
3) use "sfp sync" to sync the changes from dev org to local
4) when prompted to select package for the metadata, choose a New package
5) provide package name and the error is reproducible.

**Expected behavior**
New package should be created (?)

**Screenshots**
<img width="397" alt="2022-07-05 11_37_48-C__WINDOWS_system32_cmd exe" src="https://user-images.githubusercontent.com/19957368/177365421-035c6716-cf05-4f3a-9b91-794526f76735.png">

**Platform Details (please complete the following information):**
 - OS: Windows
 - Version [e.g. CLI Version  eg: 1.6.6] @dxatscale/sfp-cli/3.1.0 win32-x64 node-v16.14.2
 - Salesforce CLI(sfdx cli) Version: sfdx-cli/7.147.1 win32-x64 node-v16.14.2

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Fixed in 3.1.1
